// ============================================================
// report_screen.dart — compose + route manufacturer outreach
//
// Builds the templated alert body, opens mailto/WhatsApp links, or
// shares plain-text via [share_plus] (labeled “PDF report” per spec).
// ============================================================

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import 'app_theme.dart';
import 'models/scan_record.dart';

class ReportScreen extends StatefulWidget {
  final ScanRecord record;

  const ReportScreen({super.key, required this.record});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  final TextEditingController _yourName = TextEditingController();
  final TextEditingController _notes = TextEditingController();
  late TextEditingController _mfrEmail;

  String _severity = 'Moderate';

  @override
  void initState() {
    super.initState();
    _mfrEmail = TextEditingController(text: widget.record.manufacturerEmail);
  }

  @override
  void dispose() {
    _yourName.dispose();
    _notes.dispose();
    _mfrEmail.dispose();
    super.dispose();
  }

  String _bestBeforeDisplay() {
    final iso = widget.record.bestBeforeIso;
    if (iso == null) return '—';
    final d = DateTime.tryParse(iso);
    return d == null ? iso : DateFormat.yMMMd().format(d);
  }

  String _statusUpper() => widget.record.safetyStatus.toUpperCase();

  String _body() {
    final lat = widget.record.latitude?.toStringAsFixed(6) ?? '—';
    final lng = widget.record.longitude?.toStringAsFixed(6) ?? '—';
    final addr = widget.record.address.isEmpty ? '—' : widget.record.address;
    final when =
        DateFormat.yMMMd().add_jm().format(DateTime.tryParse(widget.record.scanDateTimeIso) ??
            DateTime.now());

    return '''

Dear ${widget.record.manufacturerName},

A safety concern has been detected for your product using the NovaGen SafeInk Scanner app.

PRODUCT: ${widget.record.productName}
BARCODE: ${widget.record.barcode}
BATCH: ${widget.record.batchNo}
BEST BEFORE: ${_bestBeforeDisplay()}

SAFETY SCAN RESULT: ${_statusUpper()} (${widget.record.safetyPercent}%)
Scan Date: $when

LOCATION WHERE SCANNED:
Coordinates: $lat, $lng
Address: $addr

Severity: $_severity
Notes: ${_notes.text.trim().isEmpty ? '—' : _notes.text.trim()}
Reporter: ${_yourName.text.trim().isEmpty ? 'Anonymous user' : _yourName.text.trim()}

This report was generated by NovaGen SafeInk Scanner.
INNOVATE. GENERATE. ELEVATE.
www.novagen.tech''';
  }

  String _subject() =>
      '[NovaGen SafeInk] Safety Alert — ${widget.record.productName.isEmpty ? 'Unknown product' : widget.record.productName} Batch ${widget.record.batchNo.isEmpty ? 'N/A' : widget.record.batchNo}';

  Future<void> _email() async {
    final uri = Uri(
      scheme: 'mailto',
      path: _mfrEmail.text.trim(),
      queryParameters: <String, String>{
        'subject': _subject(),
        'body': _body(),
      },
    );
    try {
      if (await launchUrl(uri)) {
        await ScanHistory.markAlertSent(widget.record.id);
      }
    } catch (_) {
      await Share.share(_body(), subject: _subject());
    }
  }

  Future<void> _pdfShare() async {
    await Share.share(_body(), subject: _subject());
    await ScanHistory.markAlertSent(widget.record.id);
  }

  Future<void> _whatsapp() async {
    final uri = Uri.parse(
      'https://wa.me/?text=${Uri.encodeComponent(_body())}',
    );
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
      await ScanHistory.markAlertSent(widget.record.id);
    }
  }

  @override
  Widget build(BuildContext context) {
    final pctColor =
        widget.record.safetyStatus == 'unsafe' ? kUnsafe : kModerate;

    Widget readTile(String title, String value,
        {Color? secondary, TextStyle? valueStyle}) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 12),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: TextStyle(color: Colors.white.withAlpha(160))),
            Text(
              value,
              style: valueStyle ?? const TextStyle(fontWeight: FontWeight.w700),
            ),
          ],
        ),
      );
    }

    return Scaffold(
      backgroundColor: kNavy,
      appBar: AppBar(
        backgroundColor: kNavy,
        title: const Text('Manufacturer alert'),
      ),
      body: ListView(
        padding: const EdgeInsets.all(18),
        children: [
          Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: kUnsafe.withAlpha(46),
              borderRadius: BorderRadius.circular(14),
              border: Border.all(color: kUnsafe.withAlpha(139)),
            ),
            child: Row(
              children: const [
                Icon(Icons.warning_amber_rounded, color: kUnsafe),
                SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Manufacturer Alert',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
                      SizedBox(height: 4),
                      Text(
                        'Safety issue detected — share responsibly.',
                        style: TextStyle(color: Colors.white70, fontSize: 13),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 18),
          const Text('Auto-filled from scan', style: TextStyle(fontWeight: FontWeight.bold)),
          const SizedBox(height: 12),
          readTile('Product Name', widget.record.productName.isEmpty ? '—' : widget.record.productName),
          readTile('Barcode', widget.record.barcode.isEmpty ? '—' : widget.record.barcode,
              valueStyle: const TextStyle(color: kOrange, fontWeight: FontWeight.bold)),
          readTile('Batch number', widget.record.batchNo.isEmpty ? '—' : widget.record.batchNo),
          readTile(
            'Safety result',
            '${_statusUpper()} • ${widget.record.safetyPercent}%',
            valueStyle: TextStyle(color: pctColor, fontWeight: FontWeight.bold),
          ),
          readTile(
            'Scan time',
            DateFormat.yMMMd()
                .add_jm()
                .format(DateTime.tryParse(widget.record.scanDateTimeIso) ?? DateTime.now()),
          ),

          readTile(
            'GPS',
            widget.record.latitude == null
                ? '—'
                : '${widget.record.latitude!.toStringAsFixed(5)}, ${widget.record.longitude!.toStringAsFixed(5)}',
            valueStyle: const TextStyle(color: kOrange, fontWeight: FontWeight.bold),
          ),
          readTile('Address', widget.record.address.isEmpty ? '—' : widget.record.address),

          const SizedBox(height: 8),
          TextField(
            controller: _mfrEmail,
            keyboardType: TextInputType.emailAddress,
            decoration: const InputDecoration(labelText: 'Manufacturer email (editable)'),
          ),

          const Divider(height: 32, color: kSlate),

          TextField(
            controller: _yourName,
            decoration: const InputDecoration(labelText: 'Your name'),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _notes,
            maxLines: 4,
            decoration: const InputDecoration(labelText: 'Additional notes (optional)'),
          ),
          const SizedBox(height: 12),
          InputDecorator(
            decoration: const InputDecoration(labelText: 'Severity'),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: _severity,
                isExpanded: true,
                items: const ['Minor', 'Moderate', 'Critical']
                    .map((e) => DropdownMenuItem(value: e, child: Text(e)))
                    .toList(),
                onChanged: (v) => setState(() => _severity = v ?? 'Moderate'),
              ),
            ),
          ),

          const SizedBox(height: 22),

          /// Share row ------------------------------------------------------
          Wrap(
            spacing: 12,
            runSpacing: 12,
            children: [
              FilledButton.icon(
                style: FilledButton.styleFrom(backgroundColor: kOrange),
                onPressed: _email,
                icon: const Icon(Icons.email_outlined),
                label: const Text('Email Manufacturer'),
              ),
              FilledButton.icon(
                style: FilledButton.styleFrom(backgroundColor: kBlue),
                onPressed: _pdfShare,
                icon: const Icon(Icons.picture_as_pdf_outlined),
                label: const Text('PDF Report'),
              ),
              FilledButton.icon(
                style: FilledButton.styleFrom(
                  backgroundColor: const Color(0xFF25D366),
                  foregroundColor: Colors.white,
                ),
                onPressed: _whatsapp,
                icon: const Icon(Icons.chat),
                label: const Text('WhatsApp'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
